### ISSUE TITLE
A little problem about 'run_swap' function

### ISSUE THREAD

**Issue by wochiyu** [moritzshore/rswap#25]
The parameter 'autoset_output' in the 'run_swap' function did not work. The output result of  'result_output.csv' is always similar as l have changed the observed variables in rswap_observed_data.csv. l detect this problem. l found that the interior of the 'run_swap' function includes a 'set_swap_output' function. In turn, the interior of the 'set_swap_output' function includes a 'load_swap_observed' function. The input parameters in the 'load_swap_observed' function do not define the parameter 'force‘. If l sets that force is True, then the 'autoset_output' can normally work.

**Comment by moritzshore** [comment]
Thank you for pointing this out. I rushed the `force` feature out the door too quickly. Let me know if the fix does not work for you or if you encounter any other problem!

**Comment by wochiyu** [comment]
Ok, l thank you very much for creating the ‘rswap’ package. By the way, can you provide some functions for optimizing parameters?

**Comment by moritzshore** [comment]
Glad that it is of use to you! Optimizing parameters is on the to-do list, however I am not sure when I will find the time to add them. 

However, they should be pretty easy to implement yourself by using [change_swap_parameter()](https://moritzshore.github.io/rswap/reference/change_swap_parameter.html), [run_swap()](https://moritzshore.github.io/rswap/reference/run_swap.html), and [get_swap_performance()](https://moritzshore.github.io/rswap/reference/get_swap_performance.html) in a loop.
