### ISSUE TITLE
Dependency package version conflicts

### ISSUE THREAD

**Issue by Pepe-oss** [moritzshore/rswap#29]
Hello，
Your work is very good, but when I downloaded it, I realised that rswap requires a hydroGOF package, however it is not compatible with r 4.2 version, whereas SWAPtools is built from 4.2.0

**Comment by moritzshore** [comment]
Hi, thanks for raising the issue.

`hydroGOF ` and its dependency `hydroTSM `were recently removed from CRAN, you can however still install them from github in the meantime, while the author works towards [re-publishing them](https://github.com/hzambran/hydroGOF/issues/20).

use the following commands to do this:

```
> remotes::install_github("hzambran/hydroTSM")
> remotes::install_github("hzambran/hydroGOF")
```

Additionally, I just tried using `SWAPtools `using R 4.3.2 and it worked, as long as all its required depencies are installed, could you provide more detail on the issue you are facing or has this info solved your problem?

**Comment by Pepe-oss** [comment]
> Hi, thanks for raising the issue.
> 
> `hydroGOF` and its dependency `hydroTSM` were recently removed from CRAN, you can however still install them from github in the meantime, while the author works towards [re-publishing them](https://github.com/hzambran/hydroGOF/issues/20).
> 
> use the following commands to do this:
> 
> ```
> > remotes::install_github("hzambran/hydroTSM")
> > remotes::install_github("hzambran/hydroGOF")
> ```
> 
> Additionally, I just tried using `SWAPtools` using R 4.3.2 and it worked, as long as all its required depencies are installed, could you provide more detail on the issue you are facing or has this info solved your problem?

Hi, I tried again to directly using 'remotes::install_github(repo = "moritzshore/rswap", ref = remotes::github_release())', the errro as follows:
`ERROR: dependency 'hydroGOF' is not available for package 'rswap'
* removing 'C:/Program Files/R/R-4.2.0/library/rswap'
Warning messages:
1: package ‘hydroTSM’ is not available for this version of R`
However, according to your commands above, I downloaded hydroTSM and hydroGOF first, then rswap can successfully download them directly. Thanks！

**Comment by moritzshore** [comment]
Glad to hear it worked, until hydroGOF is back on CRAN, this is the best method I know of currently...


purely loading an existing SWAP file can only be done seperately for parameters, tables and vectors. for parameters you would do it like so:
```
parameters <- load_swap_parameters("C:/path/to/project/", swap_file = "swap.swp")
```

See [here](https://github.com/moritzshore/rswap?tab=readme-ov-file#parameter-specific-functions) for more info.
